# Generated by Django 6.0.1 on 2026-03-12 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bovin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_bovin/')),
                ('date_abattage', models.DateField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('poids_total', models.FloatField(help_text='Poids total en kg')),
                ('type_vente', models.CharField(choices=[('kg', 'Par Kilogramme'), ('lot', 'Par Lot')], default='kg', max_length=10)),
                ('prix_par_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_par_lot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('poids_lot', models.FloatField(blank=True, help_text="Poids d'un lot en kg (si vente par lot)", null=True)),
                ('nombre_lots', models.IntegerField(blank=True, help_text='Nombre total de lots disponibles', null=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('complet', 'Complet'), ('abattu', 'Abattu')], default='disponible', max_length=20)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bovins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.FloatField(blank=True, null=True)),
                ('lots', models.IntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmée', 'Confirmée'), ('annulée', 'Annulée')], default='en_attente', max_length=20)),
                ('bovin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='bovin_market.bovin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendeur', 'Vendeur'), ('client', 'Client')], default='client', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
