# Generated by Django 6.0.1 on 2026-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovin_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovin',
            name='race',
            field=models.CharField(choices=[('zebu', 'Zébu'), ('gobra', 'Gobra'), ('djakoré', 'Djakoré'), ('ndama', "N'Dama"), ('metis', 'Métis'), ('autre', 'Autre')], default='zebu', max_length=50, verbose_name='Race'),
        ),
    ]
